### ISSUE TITLE
Странный результат get_filename_component

### ISSUE THREAD

**Issue by Ales999** [elelel/qluacpp-tutorial#1]
Не могу понять как победить

Основной каталог, где сам CMakeLists.txt, находится в C:\Dev\QluaCpp
В нем уже под-каталоги src и contrib.
Радом создал еще один, его полный путь: C:\Dev\QluaCppVS
в котором уже создал basic_tutorial_nmake
Итого полный вид при запуске герерации выглядит так:

C:\Dev\QluaCppVS\basic_tutorial_nmake>"c:\Program Files (x86)\CMake\bin\cmake.exe" -G "NMake Makefiles" c:\Dev\QluaCpp

Генерация проходит без ошибок, но вот уже компиляция NMake не идет - не может найти include файлы, в частности 'qlua'

Тогда сразу после:
get_filename_component(TOP_DIR "${CMAKE_CURRENT_SOURCE_DIR}" PATH)
добавляю:
message("TOP_DIR is ${TOP_DIR}")

Опять делаю генерацию и вижу такой вывод:
TOP_DIR is **C:/Dev**

Естественно компилятор тут ничего не найдет...

Я что-то делаю не так или надо как-то этот кусок определения переменной переделать.

Прим:
\>cmake --version
cmake version 3.8.1

**Comment by Ales999** [comment]
Пока заменил эту строчку на:
set(TOP_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
и в файле baseic_tutorial.cpp :
#include <qluacpp\qlua>

теперь NMake собрал DLL

**Comment by elelel** [comment]
Сейчас структура обучающих примеров такова, что директория каждого из них находится на 1 уровень ниже общего корневого каталога, а на одном уровне с ними есть общий для всех каталог с третьесторонними библиотеками (contrib). Сделано это для того, чтобы не копировать много раз одни и те же библиотеки (ту же qluacpp, например) для разных примеров. В итоге структура должна была бы быть примерно такой:
с:\dev\ - директория, где ведем разработку
c:\dev\qluacpp-tutorial - директория со всеми примерами
с:\dev\qluacpp-tutorial\contrib - директория, где будут библиотеки, в том числе qluacpp
c:\dev\qluacpp-tutotial\basic_tutorial - директория, где будет базовый пример, эта директория содержит CMakeLists.txt
Поэтому TOP_DIR в данном случае - директория, на один уровень выше директории, в которой находится CMakeLists.txt; эта же директория должна содержать папку contrib с остальными библиотеками. Такая структура получится, если сделать git clone репозитария. И это имеется в виду под фразой "Обратите внимание, что эта директория находится в корневой директории примеров (на один уровень выше директории этого примера)" в инструкции от базового примера.

**Comment by Ales999** [comment]
Гм,  действительно, склинило меня что он должен быть рядом, а не в под-каталоге почему-то.
Не могу найти сейчас ту ветку обсуждения, там товарищ один не не смог запустить его в QUIK-е , откуда я на этот репозитарий вышел, - есть пара мыслей:

1) Если винда X64 и у нас есть VS2015, то в нем есть только 'Командная строка MSBuild для VS2015' (которая не видит NMake) и 'Командная строка разработчика для VS2015', - в итоге код получается 64-х разрядный, что не будет работать. Я добавил вот такой блок сразу после project(...):

if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
        set(ARCH "x86_64")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "amd64")
        set(ARCH "x86_64")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64")
        # cmake reports AMD64 on Windows, but we might be building for 32-bit.
        if (CMAKE_CL_64)
                set(ARCH "x86_64")
        else()
                set(ARCH "x86")
        endif()
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86")
        set(ARCH "x86")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i386")
        set(ARCH "x86")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")
        set(ARCH "x86")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm")
        set(ARCH "arm")
else()
        message(FATAL_ERROR "Unknown processor:" ${CMAKE_SYSTEM_PROCESSOR})
endif()

Теперь DLL-ка будет 32-х разрядная.

2)  Если данную DLL планируется запускать не на машине разработчика (как в моем случае) то там банально может не быть нужных отладочных библиотек (они с "D" в конце имени).
Поэтому нам нужно это собирать как 'Release'. Для этого после (1) добавил:

set(CMAKE_BUILD_TYPE Release)

ЗЫ Спасибо за библиотеки и примеры!

**Comment by elelel** [comment]
> Если винда X64 и у нас есть VS2015, то в нем есть только 'Командная строка MSBuild для VS2015' (которая не видит NMake) и 'Командная строка разработчика для VS2015', - в итоге код получается 64-х разрядный, что не будет работать. Я добавил вот такой блок сразу после project(...):

Для собственных проектов это имеющий право на жизнь вариант. В примерах я старался по максимуму облегчить CMakeLists.txt. Даже пришлось убрать FindPackage с поиском Lua, поскольку ставит людей в тупик, когда собирают в средах где не работает. Проще убрать совсем и написать, чтоб указывали руками.

>   Если данную DLL планируется запускать не на машине разработчика (как в моем случае) то там банально может не быть нужных отладочных библиотек (они с "D" в конце имени). Поэтому нам нужно это собирать как 'Release'. Для этого после (1) добавил:
set(CMAKE_BUILD_TYPE Release) 

С этим не все так просто. Майкрософтовский компилятор имеет сцепленные флаги для указания, какой рантайм использовать (дебаг или нет, мультитрединг или нет) и для какого варианта линковки использовать: https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx. Чтоб сделать чистый релиз проект, придется тогда наверняка редактировать флаги Release типа сборки от руки. Ведь наверняка люди захотят делать статичную линковку рантайма, чтоб не нужно было на клиентский компьютер ставить Visual C Redistributable.

**Comment by Ales999** [comment]
> Я собственно просто предлагаю добавить сноску/примечание об этом, поскольку квик, если ему чего не нравится, DLL-ку  просто не загрузит, с не очень внятной причиной. 

В инструкции есть напоминание, что собирать надо кросскомпайлером, если разные архитектуры. Вообще, это само собой разумеется. Если человек хочет собирать на других архитектурах/ОС - нужно использовать кросскомпиляцию. 

> PS Не совсем понял зачем чего-то редактировать. Просто указать флаг - этого достаточно. Это как поменять статус сборки, в самой студии, и пересобрать проект, - на выходе DLL без дебага и с включенной оптимизацией.  

Release в CMake подставляет флаг с динамической линковкой к релиз рантайму, если не изменяет память. Динамическая линковка потребует установки MS Visual C redistributable на клиентской машине.

**Comment by Ales999** [comment]
Я с CMake не очень знаком,  Вам тут виднее.
Но как говорится, лучше раз увидеть чем сто раз услышать.
Я собственно вот о чем:
Это по дефолту, без флага Release:
![dependsdll-debug](https://cloud.githubusercontent.com/assets/367257/26576586/cec330ea-4542-11e7-8dd2-5cda42cacb28.png)
А вот с флагом:
![dependsdll-release](https://cloud.githubusercontent.com/assets/367257/26576595/d970ff40-4542-11e7-97c9-e1a511439487.png)

Как мы можем наблюдать если пробовать загружать DLL на обычной машине, где не ведется разработка, там банально нет Дебаг-версси рантайма. Поэтому она и не загрузится.

**Comment by elelel** [comment]
Да, можно обговорить, что рантайм, против которого линковалось динамически, должен присутствовать на машине. Но не вижу смысла, это же не обучение людей дистрибуции проектов, собранных под Студией. Но даже если бы это было обучением людей дистрибуции проектов, собранных под Студией, помимо того, что нужно ставить Release, по Вашей логике, надо и предупреждать, что нужно устанавливать Visual C Redistributable, соответствующий версии, потому что на обычной машине оно не запустится, т.к. там банально нет Релиз версии рантайма, или перекраивать флаги Release в CMake, чтоб все собиралось статично.

**Comment by Ales999** [comment]
Да понятно что это не обучение, речь идет о сборке через NMake, в студии они и сами это переключат. 
> или перекраивать флаги Release в CMake

Ничего не надо перекраивать, просто добавить упоминание [сюда](https://github.com/elelel/qluacpp-tutorial/tree/master/basic_tutorial) типа:
"Если планируете запускать данный пример на другом компе то рекомендую добавить это: 
set(CMAKE_BUILD_TYPE Release)
в Ваш CMakeLists.txt файл"

> чтоб все собиралось статично.

Кто сказал что статично получается ?
Я-ж привел пример в картинках, это как-раз динамика... 
Программа это и делает - показывает зависимости.  [Статья в википедии.](https://ru.wikipedia.org/wiki/Dependency_Walker)
Дебаг версия: **108**568 байт, релизная - **28**160 байт.

PS Не все понимают это такое CMake, и как, и что править, дабы получился VS проект.
Упоротые, типа меня , конечно докопаются  :-)
