### ISSUE TITLE
submodules qluacpp

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#10]
При клонировании репозитория происходит многократное копирование `Catch`: `contrib\qluacpp\contrib\Catch\` и `basic_tutorial\contrib\Catch\` и `\contrib\qluacpp\contrib\luacpp\contrib\Catch\`

**Comment by elelel** [comment]
Catch от qluacpp-tutorial и Catch от qluacpp это разные зависимости разных версий разных проектов
