### ISSUE TITLE
l2q_spread_bot

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#11]
Попробовал Ваш пример по спредовому боту. После запуска quik зависает, загрузка процесса на нуле. Бот выставляет сделки, однако, текущее состояние пользователь не может видеть.

![one](https://user-images.githubusercontent.com/31853792/34225455-a1619430-e5d7-11e7-89b9-a87d992579fe.jpg)
![thwoo](https://user-images.githubusercontent.com/31853792/34225463-a530d4f4-e5d7-11e7-890b-080915807fe5.jpg)
![three](https://user-images.githubusercontent.com/31853792/34225466-a9a14dde-e5d7-11e7-96ce-6e870a0c896e.jpg)

Вот что выдает дебагер
```
'info.exe' (Win32): Loaded 'C:\QUIK-Junior\lualib_l2q_spread_bot.dll'. Symbols loaded.
'info.exe' (Win32): Unloaded 'C:\QUIK-Junior\lualib_l2q_spread_bot.dll'
'info.exe' (Win32): Loaded 'C:\QUIK-Junior\lualib_l2q_spread_bot.dll'. Symbols loaded.
'info.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. Cannot find or open the PDB file.
'info.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. Cannot find or open the PDB file.
'info.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. Cannot find or open the PDB file.
'info.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\ucrtbased.dll'
'info.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msvcp140d.dll'
'info.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. Cannot find or open the PDB file.
'info.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. Cannot find or open the PDB file.
The thread 0x48d8 has exited with code 0 (0x0).
The thread 0x39d4 has exited with code 0 (0x0).
The thread 0x1c68 has exited with code 0 (0x0).
The thread 0x2784 has exited with code 0 (0x0).
```

Может требуются спецефические настройки QUIK? Или проблема в чем-то другом?

**Comment by elelel** [comment]
Проблема в том, что часть функций QLua не может в действительности вызываться одновременно. Т.е. например функцию Clear если вызывать и main скрипта и любого callback-а скрипта, то, если вызов на main скрипта произойдет до того, как OnXXX закончится, info.exe повиснет в ожидании. В спредовом боте я делал синхронизацию тремя разными способами, думая, что проблема у меня. В итоге дело закончилось вот этой темой на форуме Arqa: https://forum.quik.ru/forum10/topic3225/
Думаю, что исправлять они это не будут, потому что у тех, кто пишет на Lua такой локинг случается раз в годы и они просто перезапустят терминал. В Qlua скриптах main скрипта обычно 99% ничего не делает и ждет во вставленном в цикле sleep.

Чтоб подвисания не было, пока единственный способ, который я вижу, либо убрать эту таблицу с интерфейсом, либо сделать синхронизацию через lock-free структуру, как в log_all_trades.

**Comment by elelel** [comment]
Упростил бота - 02712e52fbf32665d7f37a4c92525daf79c6fed7
Должно работать.
