### ISSUE TITLE
.\basic.lua:1: loop or previous error loading module 'basic'

### ISSUE THREAD

**Issue by vaassi** [elelel/qluacpp-tutorial#13]
Добрый день. При запуске библиотеки из basic_tutorial получаю ошибку. 
Компилятор mingw-w64 сборка i686-8.1.0-posix-sjlj-rt_v6-rev0

В чем может быть проблема?

**Comment by elelel** [comment]
Похоже, что где-то перепутали имя lua-библиотеки (вашего dll) и имя lua-скрипта, который ее загружает. Проверьте имя файла в строчке require "lualib_basic_tutorial" lua скрипта, а так же имена библиотеки внутри dll.

**Comment by vaassi** [comment]
Дo этого у меня проект назывался просто basic.

Сделал еще раз проект с нуля без каких-либо изменений
![cmake](https://user-images.githubusercontent.com/5107627/45927953-72d45700-bf44-11e8-9287-c91c31b58e57.png)
![src](https://user-images.githubusercontent.com/5107627/45927954-72d45700-bf44-11e8-9e4e-b615f12ff5bc.png)

. Теперь ошибка другая.

единственное отличие от ваших исходников это добавление строчки
set(CMAKE_SHARED_LIBRARY_PREFIX "") в CMakeLists.txt, чтобы mingw не добавлял lib prefix вначале названия библиотеки.

**error loading module 'lualib_basic_tutorial' from file '.\lualib_basic_tutorial.dll':
	Не найден указанный модуль.**

lua скрипт и dll-ка лежат в корне квика.

**Comment by elelel** [comment]
Нужно проверить находится ли из скрипта файл dll по пути модулей. Может не находиться, например если процесс info.exe пущен с другим текущим каталогом. Как Lua ищет модули подробнее описано тут: https://www.lua.org/pil/8.1.html

**Comment by elelel** [comment]
Кроме того, если вы используете Mingw, не забывайте, что должны быть доступны все зависимости от него. На практике это значит, что библиотеки с рантаймом, которые обычно доступны при компиляции MS компилятором автоматически по пути, нужно скопировать в директорию с Квиком. У меня это LIBWINPTHREAD-1.DLL, LIBGCC-S_DW2-1.DLL, LIBSTDC++-6.DLL и возможно другие.

**Comment by vaassi** [comment]
Спасибо большое! Копирование рантайм библиотек в папку с квиком помогло. Хотя в переменной PATH путь к ним прописан, но этого оказалось не достаточно.
Посмотрел зависимости через Dependency Walker
Скопировал libgcc_s_sjlj-1.dll, libstdc++-6.dll, libwinpthread-1.dll
