### ISSUE TITLE
Кеширование lua_State* и регистрирование/дерегистрирование ф-й по запросу

### ISSUE THREAD

**Issue by Arech** [elelel/qluacpp-tutorial#15]
Привет!
Спасибо за отличный проект и серию туторов, вы просто настоящий life saver! Квик совершенно безобразен и глючен, но только наличие вашего проекта мирит с ним и даёт возможность хоть как-то его внятно использовать.

Возможно, где-то мои вопросы уже описаны, но, так же мне кажется, что тут может оказаться столько квиковой специфики, что только человек с опытом решения подобных задач может реально знать ответ.

I.
Суть первого вопроса вот в чём: мне хочется иметь возможность в своём коде подключать/отключать внутри-луашные колбеки от квика, такие как `OnAllTrade()`, `OnTrade()`, `OnOrder()` и прочие, по некоторому внешнему условию/запросу, а не только в entry point библиотеки. Можно ли это вообще делать (не "сойдёт ли квик от этого с ума"?) или колбеки обязаны быть подключены постоянно с момента старта модуля (после вызова `luaL_openlib()`) ? Ведь в обычной работе с lua скриптами квик не может ожидать, что какая-то функция то зарегистрирована/присутствует, то её нет...

Можно, конечно, их зарегистрировать все сразу, и уже внутри отдельного обработчика проверять, должны ли они быть активны в данный момент, но, наверное, это не лучший метод хотя бы по соображениям быстродействия. Та же `OnAllTrade()` может вызываться очень часто и если она реально не нужна, это, наверное, даст некий заметный оверхед? Кажется, было бы разумнее вызывать `::lua::function::OnAllTrade().register_in_lua()` / `unregister_from_lua()` в нужное время и "не платить за то, чем не пользуешься". Но вот переживёт ли это квик? Не пробовали ли Вы так делать? Есть информация, как квик это воспримет?

II.
Второй вопрос прямо связан с первым, - для вызова `register_in_lua()` / `unregister_from_lua()` требуется `lua::state&`, который в свою очередь получается из первого аргумента `lua_State*` базовой функции `luaopen_<libname>`. Можно ли закешировать этот `lua::state&` / `lua_State*` на весь срок работы библиотеки или он может в какой-то момент стать невалидным? 

(Наверное) Во все С++ функции вашего фреймворка `lua::state&` подаётся первым параметром, но я не знаю причины этого... Может быть он всегда один и тот же, может нет...

**Comment by elelel** [comment]
> I.
Суть первого вопроса вот в чём: мне хочется иметь возможность в своём коде подключать/отключать внутри-луашные колбеки от квика, такие как OnAllTrade(), OnTrade(), OnOrder() и прочие, по некоторому внешнему условию/запросу, а не только в entry point библиотеки. 

Правильный с формальной точки зрения ответ: нельзя. Документация или другие официальные источники по Quik не специфицируют, каким образом и когда он проверяет существование этих функций с заданными именами. На практике, если очень нужно: некоторые колбеки можно, некоторые нельзя. Какие можно, а какие нельзя - только проверять экспериментально для целевой версии Quik. Я пытался выяснить когда-то конкретику, но предствители Arqa не ответили. Немного более подробно об этом есть в топике, который я создал на их форуме: https://forum.quik.ru/forum10/topic2311/  Учтите только, что информация по конкретным коллбекам может быть не точна, данные от 2016 года. 

> Второй вопрос прямо связан с первым, - для вызова register_in_lua() / unregister_from_lua() требуется lua::state&, который в свою очередь получается из первого аргумента lua_State* базовой функции luaopen_<libname>. Можно ли закешировать этот lua::state& / lua_State* на весь срок работы библиотеки или он может в какой-то момент стать невалидным?

Тут такая же ситуация. Референс на lua::state - это указатель на родной объект lua. Родная библиотека lua для всего использует поинтер на свой стейт в вызовах, это форма объектной инкапсуляции, своего рода аналог this в C++. Хотя на практике как минимум в одном и том же потоке Quik используется один и тот же стейт (не помню, разные ли они там для main thread, на котором вызываются коллбеки, и script main thread; скорей всего, да), я не могу делать предположение, что в следующей версии Quik они не решат в каких-то своих внутренних целях (например, своей межпотоковой синхронизации) не пересоздавать эти объекты. В таком случае мне пришлось бы переписать весь интерфейс в одночасье, введя этот параметр, что заняло бы время и поломало бы всем пользователям библиотеки существующий код. Поэтому на практике, если очень нужно, то как минимум в колбеках один и тот же стейт и его можно кешировать. Как и на мейн треде, и его тоже можно закешировать. Но если подходить формально и учитывать, что уникальность луа объекта нигде не специфицировалась, или, если создавать задел на будущее и вероятные неприятные сюрпризы, то лучше заново цепляться каждый раз за передаваемый параметр.

**Comment by Arech** [comment]
Исчерпывающий ответ, спасибо! Вопросов больше нет... Значит дабы не закладывать под себя бомбу надо без вариантов регистрировать все колбеки и городить огород с отслеживанием состояния...

Квик конечно абсолютно уникальный софт... мдээ....
