### ISSUE TITLE
dividend_threat lib

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#19]
Добрый день.
Хочу применить Вашу библиотеку из **dividend_threat** , однако получаю следующее сообщение 

> Can't download dividend calendar at http://smart-lab.ru/dividends Downloaded http://smart-lab.ru/dividends, length 185 bytes

из метода
`bool calendar::download(const std::string& url) `

**Comment by elelel** [comment]
Посмотрите что в этих 185 байт. Наверное, сообщение об ошибке от сервера или редирект на другой адрес, потому что это писалось давно, с тех пор на smart-lab все поменялось.
