### ISSUE TITLE
convert lua_State

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#2]
Добрый день.
Спасибо за ваши разработки, весьма полезны.

Собрал проект по вашему алгоритму, описанному в basic tutorial - все работает.
Решил самостоятельно создать проект с нуля в visual studio 2017 и при сборке получил аналогичную для всех проектов ошибку:

error C2664:
'lua::state::state(const lua::state &)' : cannot convert argument 1 from 'lua_State *' to 'const lua::state &'

Reason: cannot convert from 'lua_State *' to 'const lua::state'

 Вероятно ошибка состоит в том, что в функции void my_main(lua::state& l) { ... } аргументом является ссылка на l, а в функции LUALIB_API int luaopen_lualib_basic_tutorial(lua_State *L) { ... }
указатель на стек.
Самостоятельно ошибку исправить не получается.

**Comment by elelel** [comment]
lua_State* - это тип из родного Lua API на языке C
lua::state - это обертка на C++ из библиотеки luacpp вокруг этого Lua API
Чтоб сделать из первого второе нужно поступить как указано на этой строке https://github.com/elelel/qluacpp-tutorial/blob/e66f9993c8ce7810f5065a60eed552a39c8b5517/basic_tutorial/src/basic_tutorial.cpp#L30 примера

Edit: Возможно, я неправильно понял, в каком месте возникает ошибка. Было бы проще, если бы вы привели фрагмент кода, которые не компилируется

**Comment by elelel** [comment]
Если 'lua::state::state(const lua::state &)'  - единственный конструктор lua::state::state, который студия пытается подставить при создании объекта, то по каким-то причинам в вашем проекте не доступны конструкторы из qluacpp/contrib/luacpp/src/state_base.hpp

**Comment by QApplication** [comment]
именно на этой строке и не компилируется для таких компиляторов как: MSVC 2013 (x86, x64), MSVC 2015 (x86, x64) и MSVC 2017 (x86, x64) из visual studio возникает ошибка:
error C2664:
'lua::state::state(const lua::state &)' : cannot convert argument 1 from 'lua_State *' to 'const lua::state &'

Однако, для MinGW x86 под Qt собирается. Но проекты с gui  не собираются.

**Comment by elelel** [comment]
Как минимум 2013 работать не должна, т.к. не поддерживает наследование конструкторов C++11 (https://msdn.microsoft.com/en-us/library/hh567368.aspx). В более новых проектах должна стоять поддержка C++11, чтоб наследование конструкторов из state_base.hpp работала.
Ошибка в 2013 и более поздних одинакова?
Строка создания объекта выдает только один вариант конструктора, который не подошел, с const lua::state & в сообщении об ошибке? Если да, то по каким-то причинам не происходит наследования конструктора, а студия создает имплицитный конструктор и пытается использовать его. Самое вероятно - не поддерживается С++11, но неясно, почему нет ошибки про директиву using в state.hpp. То, что вы привели - единственная строка ошибки, которую выдает студия при неудачной компиляции?

**Comment by QApplication** [comment]
файл #include "state_base.hpp" указан в файле "state.hpp". Он у меня подключен. 
error C2664: ... Это единственная строка ошибки. Создавал проект в 2017, как вы указывали в basic tutorial. Пробовал в 2015 - ошибка аналогичная.  
Почему под MinGW собирает?

**Comment by elelel** [comment]
Вы создавали через CMake и потом генерировали проект студии или проект студии с нуля?

**Comment by QApplication** [comment]
1. Создавал через CMAKE - все работает (при сборке проекта пишет что приянты правила из cmake)
2. Создавал с нуля (хотел разобраться со структурой проекта) - настройки проекта брал из CMakeLists.txt - не работает.

**Comment by elelel** [comment]
То есть, проект созданный при помощи ```cmake.exe -G "Visual Studio 15 2017"  ...``` - работает? Тогда проще всего сравнить этот проект и проект с нуля, особенно обратив внимание на то, в какой конфигурации работаете (Debug/Release) и флаги компилятора в настройках конфигурации проекта.

**Comment by QApplication** [comment]
Через cmake собирается все.
Собирал release. Сравнивал проекты ранее, на первый просмотр одинаковые, но пойду еще раз посмотрю.
