### ISSUE TITLE
Ошибка при компиляции l2q_spread_bot

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#22]
Здравствуйте. Еще раз спасибо за такую хорошую библиотеку.

При компиляции примера l2q_spread_bot в функции, приведенной ниже, регистрируется ошибка 
  b.state_->on_order(order().trans_id(),
                     **order().order_num(),** _<- констатируется ошибка - ожидается int, а передается string_
...)

Подскажите, пожалуйста выход из этой ситуации (я не рискую изменять определения)
Спасибо

void bot::on_order(const lua::state& l,
                   ::lua::entity<::lua::type_policy<::qlua::table::orders>> order) {
  std::cout << "OnOrder" << std::endl;
  auto& b = bot::instance();
  b.state_->set_lua_state(l);
  b.state_->on_order(order().trans_id(),
                     **order().order_num(),** _<- констатируется ошибка - ожидается int, а передается string_
                     order().flags(),
                     order().qty(),
                     order().balance(),
                     order().price());
  b.update_status = true;
  b.cv_.notify_one();
  std::cout << "OnOrder done" << std::endl;
}

**Comment by elelel** [comment]
В примере номер заявки следует изменить на std::string. Номера заявок были int32_t, потом на срочном рынке ММВБ их сделали не помещающимися в него, и они были переведены на строки. Библиотека обновлена, но пример обновлен не был.
Имейте так же в виду. что этот пример может быть не совсем работоспособным из-за того как в Quik устроена многопоточность.

**Comment by dima-gf** [comment]
Да, спасибо. Сейчас попробую заменить. По поводу взаимоблокировок я читал вашу ветку на форуме QUIK. Там был предложен хороший выход (на мой взгляд) - это просто в обратных вызовах только сохранять нужные данные в стеках (векторах, мапах и т.п.), а потом в основном потоке (main) их обрабатывать. По опыту работы я сам применяю такой финт (в наших программах крутится сотни потоков и взаимоблокировки встречаются). 
Спасибо за ответ.

**Comment by dima-gf** [comment]
В догонку - Ваш пример бота мне нужен только для изучения вопроса взаимодействия с QUIK. Все равно все будет писаться с нуля.

**Comment by dima-gf** [comment]
Ох - да там многовато конечно исправлений. Ну может и хорошо - пока буду исправлять может лучше и код изучу.
Но Вы уж как-нибудь потом  (для других) подправьте этот момент.

**Comment by dima-gf** [comment]
Кстати в описании таблицы они так и не исправили этот момент

order_num | NUMBER | Номер заявки в торговой системе
-- | -- | --
