### ISSUE TITLE
SetTableNotificationCallback

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#23]
Здравствуйте. НЕ подскажете, почему вы закомментировали  функцию SetTableNotificationCallback

**Comment by elelel** [comment]
Думаю, она просто не написана.

**Comment by dima-gf** [comment]
Ну, да ладно. Я подключил ATL (WTL) и теперь работаю в привычном для себя GUI (таблицы, диалоговые окна, кнопки, списки и т.п. стало доступно)
Еще раз спасибо за библиотеку и ПРИМЕРЫ - время экономится просто вагонами - да и программирование происходит в привычной среде с привычным синтаксисом.
