### ISSUE TITLE
getSecurityInfo() - рушится по exception

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#24]
Здравствуйте.
В вашем примере есть код
    // Request additional data on instrument from QLua
    q.getSecurityInfo(r.class_code.c_str(), r.sec_code.c_str(),
                      [&r] (const auto& sec_info) {
                        r.name = sec_info().name();
                        return 1;  // How many stack items should be cleaned up (poped)
                      });
 
Я этот код вял за основу и заполняю в ней не одно поле, а несколько.
Например
    q.getSecurityInfo(r.class_code.c_str(), r.sec_code.c_str(),
                      [&r] (const auto& sec_info) {
                        r.name = sec_info().name();
                        r.code = sec_info().code();
                        r.face_value = sec_info().face_value();
                        r.lot_size = sec_info().lot_size();
                        return 1;  // How many stack items should be cleaned up (poped)
                      });

И у меня срабатывает exception
Luacpp entity get: typecheck failed (Lua type at stack index -1 is nil; content as string: <Ops, got null from Lua when tried to get actual content as string>)

Что я делаю неправильно.
Пытался возвращать не 1 а количество считанных параметров - здесь 4.
Не помогает. Рушится на одной и той же записи.

**Comment by elelel** [comment]
Навскидку и судя по тексту ошибки, одно из этих полей содержит null, хотя ожидается строка. Либо испорчен луа стек (где-то ранее), либо поле действительно не содержит строку.

**Comment by dima-gf** [comment]
Спасибо. Не поясните возвращаемое значение какое все-таки должно быть - 1 или 4?
И если переданы неправильные параметры на вход в функцию - это приведет к исключению или только неправильные параметры внутри функции?

**Comment by elelel** [comment]
Вовзращаемое значение - сколько параметров надо дополнительно убрать со стека Lua после вызова лямбда-функции. Состояние стека внутри лямбда-функции ровно такое, какое оно будет в Lua после Qlua вызова и исполненного после него вашего кода. Qlua-вызов это Lua-функция. Lua-функции могут возвращать и соответственно оставлять на стеке неопределенное количество результатов (в отличие от C++, которые возвращают один результат или не возвращают нисколько, являясь процедурами). Поэтому очистить надо столько, сколько вернула функция с поправкой на ваши действия внутри лямбды (если вы сами все очистили - 0, если использовали стек и не чистили - с поправкой на это значение). В примере выше значение должно быть 1. 

К исключению привело то, что в том месте, где оно случилось, на стеке должна была быть строка, а оказался null. Это может быть по причинам:
 - Поле читается не в том месте стека (испорчено состояние стека ранее).
 - Структура Qlua, которую читаете, поменялась (например, в новой версии Quik находится по другому смещению)
 - Хотя прописана в библиотеке жестко как String, проблемная переменная на самом деле может быть null легально или полулегально. Второе, когда в документации написано, что null быть не может, но на самом деле может, вполне встречается. 

Что можно сделать:
 - Проверять перед чтением поля, что в нем содержится
 - По очереди поубирать запрос к полям и проверить исчезнет ли в какой-то комбинации баг
 - Написать тот же код на Lua и проверить, что все строки, которые запрашиваются, реально содержат строку. Учитывая, что Lua никак не остановит исполнение сама. Собственно, это источник ошибок в ботах на Lua, вся тяжесть проверки корректности возвращаемых данных лежит на программирующем.

**Comment by dima-gf** [comment]
Огромное спасибо за развернутый ответ и библиотеку.

**Comment by dima-gf** [comment]
"_Хотя прописана в библиотеке жестко как String, проблемная переменная на самом деле может быть null легально или полулегально. Второе, когда в документации написано, что null быть не может, но на самом деле может, вполне встречается_."

Как можно проверить поле на null.
Если не трудно - строчку кода напишите, ну хотя бы в свете приведенного примера (в начале блока вопроса)
r.name = sec_info().name();

**Comment by elelel** [comment]
auto field = sec_info().name;
auto c = field.lua_state().tostring(field.index());
if (c != nullptr) {
  auto str = std::string(c);
} else {
  // null!
}

**Comment by dima-gf** [comment]
Спасибо большое
