### ISSUE TITLE
Как запустить два экземпляра

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#26]
Здравствуйте. Из форума QUIK понял что запуск нескольких экземпляров - проблематично.
Подскажите что нужно переименовать в коде (хотя бы так) чтобы можно было запустить второй экземпляр.
Пробовал сначала просто разнести по двум папкам. Потом начал переименовывать 
LUALIB_API int luaopen_gf_quik_robot1 и luaL_openlib(L, "gf_quik_robot1", ls_lib, 0); - не помогло.
Ну переименовывать все экспортные функции - я конечно не стал.

При работе второго экземпляра - в лучшем случае - не работает первый - к нему перестают поступать события.
Спасибо

**Comment by elelel** [comment]
Проще всего не связываться на уровне Lua с этим вообще, а сделать поддержку внутри своего C++ кода. То есть, у вас будет некий единый С++ объект, который будет внутри себя содержать один или несколько подобъектков с конкретной реализацией логикой вашего торгового бота (или того что вы пишете). События, общение с Квиком - все через этот объект, он будет являться диспетчером между ним и внутренними экземплярами.

**Comment by elelel** [comment]
То есть типа:
```
struct Bot {
  // ...
  void onTradeEvent(data: TradeData) {
     // обработать данные в этом экземпляре
  };

  // Остальная торговая логика экземпляра бота....
};

struct MainDispatcher {
  // Эта функция регистрируется в Квике как обработчик какого-нибудь события
  static void onSomeTradeEvent(data: TradeData...) {
    ...
    // Передать данные всем живым ботам
    for (auto& copy: botCopies) {
      copy->onTradeEvent(data);
    }
  }

  void makeNewBotCopy(...) {
    copies_.push_back(std::make_shared<Bot>(...));
  }

private:
  std::vector<std::shared_ptr<BotBase>> copies_;

  // Остальная логика общения с Квик...
};

```

**Comment by dima-gf** [comment]
Спасибо за ответ.
Я хотел бы уточнить. Мне не совсем понятен ответ.
У меня именно такая структура - есть менеджер и все в нем.
Но чтобы в него передавались данные мне нужно определить перехватчики для lua - чтобы из QUIK поступали данные. Эти данные передаются в менеджер и там идет их обработка. 

Вот часть кода.
Т.е. есть класс pMainBot, в который передаются данные.

/////////////////////////////////////////////////////////////
///
//
void on_Connected2(const lua::state& l,
    tuple<::lua::entity<::lua::type_policy<bool>>> signal)
{
    if (pMainBot)
        return pMainBot->on_Connected();
}

void on_Disconnected2(const lua::state& l)
{
        if (pMainBot)
            return pMainBot->on_Disconnected();
}

/////////////////////////////////////////////////////////

LUACPP_STATIC_FUNCTION2(main, my_main2)
LUACPP_STATIC_FUNCTION3(OnStop, on_stop2, int)
LUACPP_STATIC_FUNCTION3(OnOrder, on_order2, ::qlua::table::orders)
LUACPP_STATIC_FUNCTION3(OnStopOrder, on_stop_order2, ::qlua::table::stop_orders)
LUACPP_STATIC_FUNCTION4(OnQuote, on_quote2, const char*, const char*)
LUACPP_STATIC_FUNCTION3(OnAllTrade, on_all_trades2, ::qlua::table::all_trades) // обезличенные сделки
LUACPP_STATIC_FUNCTION3(qluacpp_candles_cb, qluacpp_candles_cb2, unsigned int)
LUACPP_STATIC_FUNCTION3(OnConnected, on_Connected2, bool)
LUACPP_STATIC_FUNCTION2(OnDisconnected, on_Disconnected2)



extern "C" {
    LUALIB_API int luaopen_gf_quik_robot2(lua_State * L) {

      lua::state l(L);

    ::lua::function::main().register_in_lua(l, my_main2);
    ::lua::function::OnStop().register_in_lua(l, on_stop2);
    ::lua::function::OnOrder().register_in_lua(l, on_order2);
    ...
    ::lua::function::OnConnected().register_in_lua(l, on_Connected2);
    ::lua::function::OnDisconnected().register_in_lua(l, on_Disconnected2);

    luaL_openlib(L, "gf_quik_robot2", ls_lib2, 0);
    return 0;
  }
}

из этих функций (например on_Connected2()) вызываются функции менеджера.
Т.е. просто взят Ваш пример для сопряжения с Lua.
И я так понял, что все дело в регистрации функции. Я их переименовал - но все равно получается лажа.
Конечно я сумбурно описал - ног мне не понятно как "не связываться с Lua". 
Я просто не пойму как же тогда получать события из QUIK

Или Вы имеете ввиду - что нужно экземпляры новых ботов привязывать к общему менеджеру который получает данные из QUIK.
Но я думал как раз этого избежать - чтобы quik загружал новый экземпляр в новый поток.

**Comment by elelel** [comment]
Все функции обработчиков оставить как есть. Функция одного обработчика должна быть одна на луа-скрипт. Невозможно в Луа объявить функцию с одним и тем же названием дважды так, чтоб эта функция при втором определении не перекрыла первую. Если нужно, чтоб было много экземпляров ботов, а обработчик находится внутри класса бота, вынести функции обработчиков Луа из таких классов, у которых может быть много копий. Чтоб передавать информацию в такие классы, обработчик события, существующий в единственном экземпляре и зарегистрированный через register_in_lua() должен проходиться по списку экземпляров бота, который хранится в диспетчере, и вызывать уже собственный обработчик в экземпляре бота из себя.

**Comment by elelel** [comment]
По поводу загрузки в новый поток, Windows DLL, которая грузится в из файла .lua через LoadLibrary будет грузиться в любом случае в единственном экземпляре. Windows грузит DLL один раз, если она уже загружена, то просто увеличивает у себя счетчик. Это один из смыслов существования динамических библиотек в принципе.

**Comment by dima-gf** [comment]
Да, пока писал вам предыдущий ответ - понял Вашу мысль. Несколько прискорбно, что нельзя обычным переименованием функций и библиотек (обратите внимание - там стоит везде цифра 2 в названии) опять регистнуться в QUIK. Просто логичней было бы отдать QUIK разбираться с потоками со скриптами. Хотя наверное все равно - что QUIK будет крутить каждый экземпляр в отдельном потоке - что я буду последовательно их вызывать из одного потока (предоставленного QUIK-ом при запуске).
Спасибо за ответ и библиотеку.

**Comment by elelel** [comment]
Это можно сделать, просто проблем и труда будет гораздо больше. Например, написать Lua-скрипт, который запускает по мере надобности компиляцию библиотеки с новыми идентификаторами (всеми, которые в интерфейсе) и новыми названиями. И сделать диспетчер в нем, т.е. грузит библиотеку с нужным именем и распределяет коллбеки через себя на нужную.

**Comment by dima-gf** [comment]
Наверно Вы правы. Я, правда, не очень огорчился - т.к. структура программы написана именно так как Вы посоветовали - просто сейчас в стеке у мня один рабочий экземпляр который инкапсулирует все настройки на бумагу (и думал им обойтись). Но, просто лишний раз убедился, что структура правильная.
Спасибо.
