### ISSUE TITLE
getParamEx и getParamEx2 

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#27]
Здравствуйте.
Пытаюсь вызвать getParamEx() - но получаю исключение

Luacpp entity get: typecheck failed (Lua type at stack index -1 is string; content as string: 205.070000)

Причем цена в строке указана верно

Вот такой код

    using param_entity = const lua::entity<lua::type_policy<qlua::table::current_trades_getParamEx>>&;

    tagCmdGetParamEx2* pCmdGetParamEx2 = static_cast<tagCmdGetParamEx2*>(par1->m_Par);

    try {

        qLua.getParamEx(pCmdGetParamEx2->class_code.c_str(), pCmdGetParamEx2->sec_code.c_str(), pCmdGetParamEx2->cmd.c_str(),
            [&, this](param_entity param)
            {
                if ((param().param_type() <= 2))
                    pCmdGetParamEx2->dblRes = param().param_value();
                else
                    pCmdGetParamEx2->strRes = param().param_image();
            });
    }
    catch (std::exception e)
    {
        par1->retCode = -1;
        par1->retStr = "[IDX:CmdGetParamEx2_1163] onCmdGetParamEx2. " + string(e.what());
        writeErr(par1->retStr);
    }

Не подскажете в чем дело?

Спасибо

**Comment by dima-gf** [comment]
Разобрался

**Comment by dima-gf** [comment]
В общем сделал проще - просто использую 
pCmdGetParamEx2->strRes = param().param_image();
т.к. таблица торгов всегда открыта - то просто считываю строку и перевожу в double

**Comment by elelel** [comment]
В том поле лежит строка. Возможно, ранее там лежал double, вероятно, поменяли для точности на строку. Или всегда так было. Это типичная проблема для финансовых приложений на Lua, в какой-то момент приходится числа передавать в строках, потому что родных типов данных с заданной точностью в Lua нет. Опираться только на их param_type не стоит никогда, не только в этом случае. Внутри Lua если считать как double строку будет незаметно, она конвертнется в число, если не делать специальную проверку на содержащийся тип данных (чем в Lua редко кто-то занимается). В Qluacpp проверка на содержащийся тип данных при чтении происходит всегда. 

В конкретно данном случае не рекомендую использовать param_image(). Функция param_image() дополнительно форматирует число в соответствии с правилами Quik, что может создать проблему при конвертации строки в число. Я сделаю получение параметра с указанным явно типом .

**Comment by dima-gf** [comment]
Спасибо за ответ.
А как узнать, когда Вы это сделаете.
Просто, как я понимаю, никаких автоматических уведомлений об изменении Вашей библиотеки нет.
И не могли бы Вы тогда сопроводить исправление - примером использования.
Спасибо.

**Comment by elelel** [comment]
Сделал. Пример использования в этом коммите: https://github.com/elelel/qluacpp-tutorial/commit/e3087d6812634c70936fc50312200f218a95e2fb
Рантайм проверок не делал.

На все изменения можно подписываться средствами GitHub. Например, вам должно прийти уведомление по этому issue, если вы не отключали уведомления на почту.

**Comment by dima-gf** [comment]
Спасибо.
Уведомления мне на почту приходят.

**Comment by dima-gf** [comment]
Хотел ввести изменения в код, но компилятор (и я) не находит  функцию
 const std::string str = param.param_value_as_string();
где param - это
qlua::table::current_trades_getParamEx&

**Comment by elelel** [comment]
Вот она: https://github.com/elelel/qluacpp/blob/34e658fb05dae739b62f4767a227e1d1fddee973/src/qlua/structs/function_results.hpp#L326

Не обновили git submodules?

**Comment by dima-gf** [comment]
Спасибо. 
Не обновил, т.к. боюсь несовместимости - я же ордера все переделал на строковые.
(Правда я посмотрел историю изменений - вы тоже ордера сейчас на строковые переделали) 
И плюс - сейчас рабочая версия ботика - не хочу делать резких движений.
Но со временем - обновлю.
Нужно только решиться ;)

**Comment by dima-gf** [comment]
Спасибо.
Работает.
Правда, теперь работает там где раньше не работало.
Дело в том, что раньше (до изменений) в этом месте
            if ((param().param_type() <= 2))
                pCmdGetParamEx2->dblRes = param().param_value();
несмотря на то, что type <=2   программа выдавала exception().
Теперь - все нормально - т.е. до функции
param.param_value_as_string(); дело не доходит.
Правда версия поменялась на QUIK 8.8.0.55 - где они перешли на LUA 5.3. - может что то в Lua исправлено или в самом QUIK
