### ISSUE TITLE
Lua 5.3

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp-tutorial#28]
Здравствуйте.
Сегодня заменил QUIK, который перешел на Lua5.3.
При переходе на Lua 5.3 
Компилятор не находит функцию luaL_openlib(),
и не знает структуру luaL_reg и функцию luaL_getn.
Не подскажете, как в этом случае регистрировать свою библиотеку?
Спасибо

**Comment by elelel** [comment]
Как именно "не находит"? Вот в этом пункте: https://github.com/elelel/qluacpp-tutorial/tree/master/basic_tutorial#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-lua  скачали Lua 5.3?

**Comment by elelel** [comment]
В 5.3 вместо openlib видимо luaL_newlib  http://www.lua.org/manual/5.3/manual.html

https://stackoverflow.com/questions/19041215/lual-openlib-replacement-for-lua-5-2

**Comment by dima-gf** [comment]
Нашел в интернете ответ и сделал такой код
#ifdef _LUA53_
static struct luaL_Reg ls_lib[] = {
  { NULL, NULL }
};
#else
static struct luaL_reg ls_lib[] = {
  { NULL, NULL }
};
#endif

...

#ifdef _LUA53_
    lua_newtable(L);
    luaL_setfuncs(L, ls_lib, 0);
    lua_setglobal(L, "gf_quik_robot1");

#else
    luaL_openlib(L, "gf_quik_robot1", ls_lib, 0);
#endif

-  заработало. Теперь даже при выключении скрипта (штатно или из программы) нет исключений (раньше все время были).
О - во втором Вашем ответе как раз эта ссылка и указана откуда взял код.

**Comment by Arech** [comment]
Парни, привет. Сейчас портирую свой [проксик](https://github.com/Arech/t18qsrv) на Lua5.3 и после внесения правок @dima-gf наблюдаю так же сбой компиляции в [quik_thread_safe.hpp строка L45](https://github.com/elelel/qluacpp/blob/34e658fb05dae739b62f4767a227e1d1fddee973/src/qlua/extended/quik_thread_safe.hpp#L45)
```c++
 auto len = luaL_getn(l.C_state(), -1);
```
Поиск по инклудам lua показывает, что функция `luaL_getn` определена только в Lua5.1. Судя по [мануалу](https://www.lua.org/manual/5.1/manual.html#7.3), она устарела уже в 5.1 и заменена на `lua_objlen`. В 5.2 она была [переименована](https://www.lua.org/manual/5.2/manual.html#8.3) в `lua_rawlen`.

Сигнатуры:
```c++
//старая
LUALIB_API int (luaL_getn) (lua_State *L, int t);
//новая
LUA_API size_t          (lua_rawlen) (lua_State *L, int idx);
```
Т.е. в данном контексте различия не существенны и можно просто заменить одно имя на другое.
Так же добавлю к предыдущему коменту, что необходимо сделать `#define LUA53` перед инклудом `#include <qluacpp/qlua>`.

После этих правок начинает собираться и падает уже от того, что номер обезличенной сделки внезапно стал отдаваться как `::std::string` вместо целочисленного типа... Вроде как Арка переходила на Луа5.3 для поддержки десятичных 19-значных номеров сделок и 19 десятичных знаков это аккурат 64 бита, т.е. обычный `::std::uint64_t` - то, что надо. @elelel , почему Вы решили отдавать эти и некоторые другие судя по исходникам, данные как строки? Там действительно могут быть не-64битные данные?

UPD: и вот смотрю QLua.chm для версии 8.8, пишут `trade_num | NUMBER | Номер сделки в торговой системе`, т.е. вроде как числом, а не строкой, должно отдаваться... Почему строка? Можно ли изменить на uint64_t ?

**Comment by Arech** [comment]
И смежный вопрос: вы реализовали поддержку целочисленных типов в `luacpp` посредством семейства `isnumber/tonumber/pushnumber` функций. Тип number в lua соответствует числу с плавающей точкой, обычно `double`, а для целочисленных есть тип integer, который разворачивается обычно в нормальный `long long`, т.е. правильное, хоть и знаковое, 64битное целое.

Естественно, ни в какой `double` 64 битное целое не влезет, - это единственная причина почему 64битные числа вы решили обрабатывать как строки?

А можете вспомнить, что было причиной исходного решения работать со всеми числами как с плавающей точкой? У вас очень красиво разведена типизация через классы `lua::detail::integral` vs `lua::detail::floating`, которые позволяют иметь совершенно независимый хендлинг плавающей точки и целых, но тем не менее, они имеют идентичную реализацию через вышеупомянутое семейство `lua_*number()`... Учитывая всю проведённую Вами работу мне как-то трудно поверить, что у этого нет каких-то серьёзных причин. Можете вспомнить, почему так сделано?

Если я исправлю `lua::detail::integral` на использование луа-типа integer и соответственно, добавлю поддержку 64битных целых, чем я рискую?

**Comment by elelel** [comment]
Я пока не могу подробно ответить, потому что деталей уже не помню, и мне нужно время чтобы посмотреть код, которого прямо сейчас у меня нет. Но примерно ситуация такая:

- Если я правильно помню, Quik долгое время был на Lua 5.1 и перешел на Lua 5.3, поэтому состояние Lua API 5.2 практически не учитывается - либо 5.1, либо 5.3
- Факт перехода на 5.3 или на 64-битный Quik в последней релиз версии от Arqa не означает, что эта версия везде используется. Например, Альфа-Банк (Альфа-Директ) использовал в продакшене вообще 32х битный Quik менее чем год или поглода назад (возможно использует и сейчас, я давно не интересовался). Учитывая это, а также вариабильность поведения Quik (особенно мэппинг типов данных), qluacpp писалась так, чтоб поддерживать наиболее широкий набор различных вариантов клиента. 
- Переход на длинные идентификаторы сделок никак не коментировался Arqa в плане внутреннего технического представления. Конечный размер длины (19 символов, как вы указали) не подтверждался разработчиками. В 32х битных версиях Quik поддерживаются длинные идентификаторы, в 32 бит не влезающие. Как бы в Arqa ни решили представлять внутри данные, они практически неизбежно должны будут поддерживать приведение их к строки, чтоб этим всем можно было пользоваться хотя бы из их же Lua. Конвертация в строку - гарантированный способ получить данные из Lua, которая потенциально патчилась Arqa в сооответствии со своими требованиями представления типов 64-битной размерности, точности и др. 
- Floating проблемны в Lua сами по себе, потому что оригинально Lua исходит из наивного предположения, что С тип данных для приближенных вычислений может быть использован как заменитель типа данных для точных вычислений. Это очевидная проблема, которая отражена в том числе в родном Qlua интерфейсе - ряд таких полей получается/возвращается как STRING. В более менее здравых системах, имеющих дело с деньгами, внутри используются типы данных с заданной точностью, а в их Lua интерфейсах конвертируются в number с double внутри исключительно в силу ограничений Lua и в случаях, когда точностью представлений, по мнению разработчиков, пользователь может принебречь.
- number/integer lua_isinteger это попытка выйти из ситуации, когда по дефолту любой число представлялось внутри как double. В 5.1 (на которое почти все таргетировалось) не существует integer.  С одной стороны они не могли себе позволить заменить базовый тип number на два типа, это кардинально меняет основы их системы типов данных. другой стороны они хотели дрейфовать в сторону "нормального" языка. Поэтому тип number остался в 5.3, но добавилась ремарка что "The type number uses two internal representations, or two subtypes, one called integer and the other called float." Интерфейс Qluacpp построен на документации qlua.chm где тип заявляется в терминах базовых типов Lua, то есть как NUMBER. Хелп файл полуавтоматически парсится, проверялся скриптом, т.к. данные из него часто не соответствуют действительности (см type_consistency), какой из NUMBER целочисленный угадывалось ситуативно. По умолчанию тип считался double, т.к. внутри он должен был быть в 5.1 неизбежно double в любом случае.

**Comment by Arech** [comment]
> В 5.1 (на которое почти все таргетировалось) не существует integer

Это была моя первая гипотеза, однако она не потвердилась. В 5.1 был и есть [integer](https://www.lua.org/manual/5.1/manual.html#lua_Integer), pushinteger/tointeger (но, кажется, нет isinteger, однако его наличие вроде не критично). Поэтому я думал, что были какие-то ещё соображения на этот счёт...

> Qluacpp построен на документации qlua.chm где тип заявляется в терминах базовых типов Lua, то есть как NUMBER.

Да, я так и предполагал. Судя по тектовым совпадениям и стилю, большие части qlua.chm созданы просто копи-пастом соответствующих частей описания реликтового QPile. Я думаю именно оттуда и пошло написание number капсом, как в QPile. В самой же луа такого нет.

Есть у меня большое подозрение, что всё это - артефакты реликтового кода. В любом случае, я пока не вижу причин, почему нельзя попробовать изменить определение `lua::detail::integral` на использование lua_integer и сделать поддержку int64. Биржа же вроде как гарантирует, что идентификаторы 64битные? Тогда квик обязан оставлять их таковыми не важно каким представлением он пользуется. Значит даже если в луа лежит строковое представление, lua_tointeger вернёт корректный int64, выполнив конверсию, а нам иного и не надо. Плюс избежим накладных расходов на все тормоза с аллокацией строк, которые потом всё равно будут превращены в 64 бита.... Тормозной квик это не спасёт, но куда его ещё замедлять...

Напишу потом, что получилось.

UPD: но если вам важно иметь поддержку 32х-битных версий, то да, боюсь, придётся оставить. Впрочем, возможно, уже не осталось брокеров, кто ещё поддерживает 32 бита (ГПБ, например, их давно удалил.)

**Comment by elelel** [comment]
В 5.1 push_integer это для тех кто пишет свое нестандартное представление чисел. По стандартному представлению number сравните пункт 2.2 в референсе от 5.1 и 5.3:
https://www.lua.org/manual/5.1/manual.html 
https://www.lua.org/manual/5.3/manual.html 

isinteger критичен для типобезоасной работы. В политиках типов luacpp данные не только извлекаются, но и проверяются на соответствие. Именно таким образом и выявлялись неточности в документации, а также в самой реализации Quik, когда тип "мутирует" в другой в разных местах Quik.

Биржа гарантирует, но Arqa не гарантирует. Неизвестно, как Arqa хранит эти идентификаторы. Неизвестно, хранят ли они в Quik их вообще как числа. Неизвестно, что они делают, чтоб хранить их кросс-платформенно.Если это некий int,  хранится ли оно в обычном int64_t (long long для 32 бит)? Или это свое представление? Сохраняет ли их тип ABI ( компиляторы Quik и qluacpp приложения могут быть разными)? Или это вообще строки, ведь Quik это платформа не только для MOEX, может они решили ввести универсальный трансплатформенный идентификатор и поэтому он потенциально не числовой?

**Comment by Arech** [comment]
> По стандартному представлению number  ...

Спасибо, интересное дополнение. Оттуда из 5.3

>Lua has explicit rules about when each representation is used, but it also converts between them automatically as needed (see §3.4.3). Therefore, the programmer may choose to mostly ignore the difference between integers and floats or to assume complete control over the representation of each number.

Т.е. если в дальнешем число всё равно используется как 64битное целое (потому что оно такое должно быть), то разумнее и проще его получать сразу таковым от Луа.

> isinteger критичен для типобезоасной работы. 

Да, понимаю. Но если очень хочется, всегда можно сделать "закат солнца вручную" - извлечь строковое представление, на которое нет ограничений, и проверить ручками, похоже ли оно на int. Если учесть способ записи интов, совместимый с генератором строк луа, что вряд ли сложно, т.к. он должен быть абсолютно стандартный, проблем доставить не должно. Но да, наверное, соглашусь, что в 5.1 можно было и просто забить.

> Биржа гарантирует, но Arqa не гарантирует.... ведь Quik это платформа не только для MOEX, может они решили ввести универсальный трансплатформенный идентификатор и поэтому он потенциально не числовой?

Думаю, вот тут не совсем так. Если Арка позволит себе менять, например, идентификаторы обезличенных сделок, то брокеры и, как следствие, сама Арка рискуют нарваться на обоснованные обвинения в кухонности, когда совершённые через одного брокера сделки невозможно увидеть в другом. Кмк, это уже серьёзно и они на это не пойдут. Сейчас же Вы можете спокойно как увидеть свои сделки в терминале другого брокера, так и выгрузить их в истории, собранной третьими лицами. Поэтому, по меньшей мере, относительно бирже-уникальных идентификаторов, я не вижу никаких причин думать, что Арка станет их изменять. Скорее всего это даже просто юридически невозможно. (хотя пруфлинков у меня навскидку нет).

Брокеро-специфичные идентификаторы - соглашусь, что теоретически могут быть любыми, однако я опять не знаю причин, почему они не должны быть наиболее простыми и эффективными объектами - целыми числами. В конечном итоге они все являются primary key в очень нагруженных таблицах СУБД, и я сильно удивлюсь, если они не ~int64. Арка, конечно, не раз давала повод удивиться, но...кмк, одной теоретической возможности "могут сделать" не достаточно, чтобы реально ожидать этого.

> Сохраняет ли их тип ABI ( компиляторы Quik и qluacpp приложения могут быть разными)?

Я не знаю ни одного примера разной семантики 8-16-32-64 битных целых, как и float/double, в разных ABI одной процессорной архитектуры. И удивлюсь, если они вообще есть. В конечном счёте это же просто содержимое процессорного регистра, которое всегда определено и используется однозначно процессорными же инструкциями. ABI это про интерфейс, а "раз скомпилировалось, значит ABI сходится", иначе зачем вообще все эти лютые name-mangling нужны?

Поэтому резюмируя... Вопросы хорошие, правильные и по делу, но всё таки, мне кажется, что в условиях, когда относительно некоторого бирже-специфичного поля известно:

1. QLua документация говорит про число (пусть целое/нецелое - неясно)
2. Биржа говорит про целочисленное значение (Арка не может подменять значение чужого поля)
3. dll-плагины для QLua задуманы собираться с совершенно стандартным lua-SDK (это накладывает обязательство совместимости получаемых бинарниками ABI)

я не вижу причин, почему не нужно извлекать значение поля в 64битное число. Попробую, потестирую, расскажу...

(для уточнения: я не настаиваю ни на каком внесении изменений в Ваш проект, но если Вы посчитаете, что мои аргументы помогут его усовершенстовать, я буду рад).

**Comment by elelel** [comment]
Сам факт использования Lua означает трансформацию числовых данных в менее репрезентативные, чем имеется изначально в биржевой системе. Ни к каким проблемам легального толка это не приводит.

Сделать 64 битный тип с неэквивалентным ABI для 32 архитектуры очень просто:

```
// Условно портируемый (для 32 битной архитектуры и если не учитывать порядок/эндиан) и эквивалентный
struct my_int_64_a {
  int32_t hi; int32_t lo;
};
// Условно портируемый, но не эквивалентный, не может быть передан в регистрах, например.
struct my_int_64_b {
  my_int64_t_b(a:int32_t, b: int32_t) : hi{a}, lo{b} {};
  int32_t hi; int32_t lo;
};
```

В рамках одной архитектуры float вполне могут быть с разным ABI. Наример ARM - архитектура одна, а скомпилировать можно с hard или soft ABI.

Решение тут очень простое, просто сделать #if LUA_VERSION .... в соответствующих местах. Вы задали вопросы, на которые я отвечал, это не касалось решений.

**Comment by Arech** [comment]
Мы ведь не работаем со структурами напрямую, а вызываем ` __cdecl tointeger()`, которая возвращает целочисленный ответ строго в соответствии со своей __cdecl ABI спецификацией. Иначе бы мы не могли "женить" длл-ки и lib-ки от разных компиляторов. Так что совместимость ABI - последнее, что меня тут беспокоит... Ладно, не суть важно и принципиально.

Попробовал реализовать `lua::detail::integral` через `integer` и получил уже падения от тайпчеков `isinteger()` на данных вида `1.0`, которые скорее всего и должны быть целыми, просто по какой-то причине (предположу "лень и удобство") выкладываются квиком в луа через pushnumber(). Возиться дальше пока не стал, просто реализовал доп. класс, аналогичный `lua::detail::integral` для int64 через integer-api и задействовал его для номеров сделок. Пока вроде всё хорошо.

**Comment by elelel** [comment]
Вы правы, унесло меня с этими всеми непонятными аналогиями про ABI.
Если вы хотите произвести разбиение number на integer/float, советую прогнать type_consistency и считать, что все, что по факту float (как 1.0) - флоатом. Правда это будет постоянно меняться, а выигрыша от этого особого нет. Кстати, если вам нужна скорость на идентификаторах, которые сейчас в виде строк, можно их конвертировать на pmr (сравнительно небольшие затраты труда).

**Comment by Arech** [comment]
> ABI

Да это пустяки, для того и общаемся...

---

Про type checking & conversion мне 2 момента видятся...

Первый... Сказать по правде, мне, вообще, не очевидна полезность безусловной проверки типа, например, при каждом получении значения поля таблицы. Для дебужной версии это однозначно важная и полезная штука, ибо контроль собственных предположений о состоянии программы - первичное и одно из самых эффективных средств отладки и поиска ошибок. Но в релизе оно зачем? Что может измениться в детерминированном отлаженном алгоритме, из-за чего при разборе миллиона строк всё сработает чисто, а на миллион первой выбросится исключение? (которое скорее всего, к тому же, будет иметь эффект ассерта, т.е. вывалится на самый верх стека в единственный корневой хендлер, выведет ошибку и завершит программу, ибо, повторю, какие основания ожидать недетерминированность в детерминированном алго с детерминированными и/или ранее проверенными входами ?)

Причём про миллион строк я не просто так сказал, у меня конкретный юзкейс - с помощью [проксика](https://github.com/Arech/t18qsrv) и [плагина](https://github.com/Arech/Q2Ami) я переношу весь поток обезличенных сделок нужных инструментов из Квика в AmiBroker, где его гораздо удобнее, проще и эффективнее анализировать. Если я подключаюсь ближе к вечеру, то всего несколько инструментов легко успеют наколбасить больше миллиона сделок за день. На каждую сделку пусть 10 обращений к полям таблицы, итого 10 миллионов вызовов type checking, которые никогда не будут сбоить. А если ещё хотя бы одно из полей строковое, то будет миллион вызовов условных malloc/strcpy/free только на life cycle строк, плюс ещё столько же на каждое копирование строки (а только один компилятор знает сколько их там, потому что в QLuaCpp передача по значению - весьма частое явление и явно не все и них компилятор может оптимизировать). И все не это считая потом миллиона вызовов условных sscanf для получения обычного числа. И всё это работает в UI потоке квика, потому что вот такая его гениальная архитектура. Естественно, первый запрос данных заметно всё тормозит ~~штоашпичот~~. И главное - всё это лишнее, потому что см. выше.

Момент номер полтора: мы проверяем типы, а почему не проверяем диапазон, когда кастим к меньшему типу, вроде double -> int или unsigned? Тут ведь простор для косяков даже в отлаженном детерминированном алго, мы не знаем внутреннего представления квика и только предполагаем int там где мог быть и int64, например. Или стал впоследствии без должного предупреждения или мы то предупреждение проморгали. Да, у MSVC есть /RTCх, но вот только оно не совсем стандартное и не всегда используется даже при отладке. И, кажется, не хендлится как исключение (а если хендлится - кто об этом вообще подумает?).
Т.е. проверки вроде и есть, но какие-то немножко не полные, в реальности не совсем надёжные и весьма тяжеловесные.

Второй момент:

> что все, что по факту float (как 1.0) - флоатом

А почему вдруг мы рассматриваем тип внутри луа как первичный===реальный тип данных? Это ж эрзац реального типа, который всегда будет меньше/проще или в худшем случае равен типу луа. Ведь по сути от того, что ленивая или просто недальновидная Арка пихает целочисленное по определению число знаков после запятой в цене внуть double для луа, это число не становится вещественным. И не станет никогда...

**Comment by elelel** [comment]
> не очевидна полезность безусловной проверки типа

Это главная цель qluacpp библиотеки. Проблема с Lua в торговом терминале это колоссальные препятствия в контроле корректности кода. Иначе можно было бы писать и просто сразу на Lua. Идея состояла в том, что если надо быстро, можно лезть в стек Lua напрямую, во всех остальных случаях, которых большинство работать через проводящие проверки адаптеры.

> Что может измениться в детерминированном отлаженном алгоритме

Завтра Arqa поменяет 1.0 на 1 на уровне типа данных в каком-то поле и детерминированность отлаженного алогритма нарушится, причем только для тех кто работает на нативном уровне. Для самих Arqa, которые не используют Lua-ужас или для пользователей, которые используют Lua-ужас исключительно в приведенных динамических типах, это вообще не будет заметно.

>  А если ещё хотя бы одно из полей строковое, то будет миллион вызовов условных malloc/strcpy/free только на life cycle строк, плюс ещё 

Если случаются ботлнеки из-за реальных бизнес-требований, следует напрямую работать с lua (сказано где-то в тьюториалах). Или сделать свой адаптер строк для std::pmr::string (в оригинале не делалось из-за древности кода, сейчас я бы делал исключительно с полной поддержкой темплейта std::string, вместо конкретного типа)

> а почему не проверяем диапазон, когда кастим к меньшему типу, вроде double -> int или unsigned

Не понял. Если речь идет о данных из Qlua то там куда более крупные проблемы чем с диапазонами или знаковостью. Вы например писали, что ид транакции 19 числовых знаков. А когда в свое время задавался такой вопрос Arqa, они подтвердить это отказались, сказав только, что оно будет поддерживать такие ид. Если речь идет о коде на C++, внутри библиотеки, то он собирался с -Wall -Werrror и MSVC эквиваленте.

> мы не знаем внутреннего представления квика и только предполагаем int там где мог быть и int64, например

Не знаем, поэтому там где есть большие сомнения, числа передаются в строках. Например, идентификатор биржевой транзакции, относительно внутреннего представления которого были очень большие вопросы как минимум на 32х квиках.

> А почему вдруг мы рассматриваем тип внутри луа как первичный===реальный тип данных

Zero-cost abstraction principle для избежания копирования и того, что происходит со строками

**Comment by JaydenSu** [comment]
Библиотека не рабочая.

**Comment by master-lame-master** [comment]
Библиотека не рабочая для версии Lua 5.4
Проект заброшен. Можно выбрасывать. И писать с нуля что-то свое, основываясь на поддерживаемых байндингах, взяв из другого не российского проекта, где следят за обновлениями.
Автор похоже сам откуда-то взял изначальные обертки байндингов, переписал так, что не узнать, но не сказал нам откуда брал. А там наверняка давно пофиксили и для версии 5.5. Потому что только дурак будет писать с нуля, когда обертки и так существуют в природе.
И прикрутил неймспейсы для функций именно QLua и таблиц квика с типами данных. Важная работа, но это только пол дела.
В общем, получился не рабочий огрызок.

**Comment by master-lame-master** [comment]
Работает на Lua 5.4
Разобрался, два дня потратил! Очень смешная и вообще-то очевидая ошибка.
Вполне исправляется.
