### ISSUE TITLE
api for qlua

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#5]
Вопрос!
Зачем в каждом callback чтобы обратиться к стеку VM lua необходимо вызывать конструкцию типа: 
`qlua::api q(l`); где l - `lua::state`. Можно ли создать в начале скрипта один указатель на api типа: 
`lua::state *state_Lua   = new lua::state();`
`qlua::api *api_QLua    = new qlua::api(*state_Lua);`
и передавать в функцию callback'ов только указатель? Уменьшиться время выполнения callback?

**Comment by elelel** [comment]
Это сделано потому, что Qlua недоспецифицирована. Т.е. нигде не сказано, что каждый раз в каждом коллбеке мы будем получать от Quik тот же state каждый раз, хотя на практике сейчас так и будет. Но если, например, по каким-то причинам в каких-то случаях разработчики Quik решат делать новый стейт, то это порушит все скрипты, написанные при помощи моей библиотеки (в то время как пользователи Lua скриптов ничего даже не заметят).
Если вы осознаете такой риск и уверены, что lua_state* будет один и тот же, можно создавать от него lua::state и кешировать, как и qlua::api от qlua::state. 
Объекты lua::state/qlua::api сверхлегкие, никакого выигрыша по производительности кроме, возможно, пары копирований uintptr, которые даже замерить на современных процессорах не получится, вы не добьетесь. Единственный плюс, который вижу - визуально не будет лишних "повторений" в исходном коде.

**Comment by QApplication** [comment]
Факт изменения state можно отследить версионностью библитеки lua5.1.dll и соответствубщим падением Quik?

**Comment by elelel** [comment]
Будет меняться не прототип lua_State, а объект. Т.е. указатель будет не один и тот же. Со статическими версиями кода это никак не связано. Если начать работать не над тем объектом State, скорей всего начнутся ошибки, которые невозможно диагностировать напрямую, например, с сообщениями, что не тот тип данных был обнаружен на какой-то глубине стека. В целом, такой подход в любом случае противоречит написанию "чистой" библиотеки. Если C API сверху нам передает объект каждый раз, никаких дополнительных умозаключений о том, что этот объект будет одним и тем же в каждом вызове мы формально не имеем права делать.
