### ISSUE TITLE
development qluacpp

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#7]
В [basic_tutorial](https://github.com/elelel/qluacpp-tutorial/tree/master/basic_tutorial#Компилятор) указано, что qluacpp **В ДАННЫЙ МОМЕНТ** является header-only библиотекой. Каким будет дальнейшее развитие проект библиотеки?

**Comment by elelel** [comment]
Это указано, потому что до того момента она таковой не являлась. Возвращать ее к предыдущему состоянию я не планирую.
