### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp-tutorial#8]
TRANS2QUIK_DLL: в мануале описано 18 функций, в dll имеется 68. Где можно взять оставшееся описание? Вы собираетесь использовать эту dll?

**Comment by elelel** [comment]
Trans2quik не имеет никакого отношения к библиотеке, это отдельный от Lua, гораздо более старый интерфейс. Задавать вопросы по ней лучше на форуме Quik. По транзакциям я возможно добавлю только интерфейс к соответствующей Lua функции.

**Comment by QApplication** [comment]
Можно на мне понятном языке: вы будете оборачивать только те функции из Trans2quik (разработки Арки технолоджи), которые приведены в описании мануала? Вы еще не работали в этом направлении?

**Comment by elelel** [comment]
В библиотеке qluacpp я буду оборачивать только то, что есть в QLUA. Там есть посылка транзакций, о которой мы говорили в другом issue, если она так нужна, то возможно оберну ее. Но оборачивать trans2quik в библиотеке qluacpp я точно не буду, потому что она не имеет к ней отношения.

**Comment by elelel** [comment]
Вспомнил, почему я не стал начинать sendTransaction. Я хотел сделать, чтоб .tri структура была целиком на типах, а не на строках. В этом случае синтаксически неправильно составленная транзакция бы ловилась бы на стадии компиляции, а не когда уже транзакцию отсылаешь в Quik. Но это оптимально было бы сделать на С++17, который обещают официально объявить стандартом до конца года, но никак не объявляют. Заставлять людей переходить на экспериментальный стандарт в случае этой библиотеки тоже не хотелось бы.

Добавил sendTransaction(...), но не тестировал. В качестве аргумента принимает std::map<ПАРАМЕТР, ЗНАЧЕНИЕ> (оба элемента - std::string).
